officers:
  - name: "Joe Allen"
    position: "Commander"
    filter: "Command"
    image: "allen.jpg"
  - name: "Patrick Pierson"
    position: "Sr. Vice Commander"
    filter: "Command"
    image: "pierson.jpg"
  - name: "Wayne DeLauter"
    position: "Jr. Vice Commander"
    filter: "Command"
    image: "delaughter.jpg"
  - name: "Kenny Rizzo"
    position: "Adjutant"
    filter: "Operations"
    image: "blur.jpg"
  - name: "Dale Blake"
    position: "Quartermaster"
    filter: "Operations"
    image: "dale.jpg"
  - name: "Nathan Robinson"
    position: "Chaplain"
    filter: "Services"
    image: "robinson.jpg"
  - name: "Jay Martinez"
    position: "Surgeon"
    filter: "Services"
    image: "martinez.jpg"
  - name: "Jim Burdette"
    position: "Service Officer"
    filter: "Services"
    image: "burdette.jpg"
  - name: "Hugh Warner"
    position: "Judge Advocate"
    filter: "Operations"
    image: "warner.jpg"
  - name: "Ron Turley"
    position: "2nd Year Trustee"
    filter: "Trustees"
    image: "turley.jpg"
  - name: "Dan Campbell"
    position: "3rd Year Trustee"
    filter: "Trustees"
    image: "campbell.jpg"

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

gems:
  - jekyll-sitemap

# Site settings
title: VFW Post 3285
subtitle: "John R. Webb VFW Post 3285"
url: "https://www.vfw3285.org" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
newsletter: "https://us8.campaign-archive.com/home/?u=bf686e4d27915b21ce1cf42bf&id=d608a5130b"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-92630193-1"

google:
  tag_manager:
    container_id: GTM-MT9RKR2

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
