version: 0.2

phases:
  install:
    commands:
      - gem update --system
      - gem install bundler
      - gem install jekyll
      - bundler update --bundler
      - bundle install
  build:
    commands:
      - make html
  post_build:
    commands:
      - make pushupdate
